version: '3.4'

services:
  adfenix.campaignserversmock:
    container_name: adfenix.campaignservers.mock
    build:
      context: ../
      dockerfile: /Adfenix.CampaignServersMock/Dockerfile
    ports:
      - '8999:8999'
    networks:
      - adfenix-network

  adfenix.visualizermock:
    container_name: adfenix.visualizer.mock
    build:
      context: ../
      dockerfile: /Adfenix.VisualiserMock/Dockerfile
    ports:
      - '8998:8998'
    networks:
      - adfenix-network

  adfenix.zendeskmock:
    container_name: adfenix.zendesk.mock
    build:
      context: ../
      dockerfile: /Adfenix.ZendeskMock/Dockerfile
    ports:
      - '9000:9000'
    networks:
      - adfenix-network

networks:
  adfenix-network:
    name: adfenix-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24